### ISSUE TITLE
"MOL Romania" is spelled "MOL Rom?nia"

### ISSUE THREAD

**Issue by di-popa** [sebiboga/InternshipTM#14]
ENVIRONMENT: PROD
   URL: https://shaqodoon.ro/companii
   Browser: Chrome

STEPS TO REPRODUCE:
   1) Open URL in Browser
   2) Click on "Companii"
   3) Check the company "MOL Romania"

EXPECTED RESULTS: 
   The company should be spelled: "MOL Romania"

ACTUAL RESULTS: 
   The company is spelled "MOL Rom?nia"

**Comment by sebiboga** [comment]
@di-popa nice!
good spot!

**Comment by sebiboga** [comment]
@di-popa fixed. Please RETEST!

**Comment by di-popa** [comment]
The company name is displayed correctly "MOL Romania".

**Comment by sebiboga** [comment]
thank you @di-popa
