### ISSUE TITLE
ISJ tile does not open a page with valid jobs

### ISSUE THREAD

**Issue by di-popa** [sebiboga/InternshipTM#5]
ENVIRONMENT : PROD
    URL: https://shaqodoon.ro/companii    
    browser: Chrome

STEPS TO REPRODUCE:
   1) Open URL in browser
   2) Scroll down to ISJ tile
   3) Click on ISJ tile

EXPECTED RESULTS:
   A page with jobs is opened

ACTUAL RESULTS:
   No jobs are displayed

**Comment by rcordea** [comment]
I fixed this issue, please RETEST.

**Comment by rcordea** [comment]
Retested on PROD ENVIRONMENT.
This issue has been fixed
Closing the Bug
